version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=http://localhost:8001
    depends_on:
      - api
      - websocket

  api:
    build: ./api
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    depends_on:
      - redis

  websocket:
    build: ./websocket
    ports:
      - '8001:8001'
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    depends_on:
      - redis

  notion-recorder:
    build: ./notion-recorder
    environment:
      - NODE_ENV=development
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_GAMES_DATABASE_ID=${NOTION_GAMES_DATABASE_ID}
      - REDIS_URL=redis://redis:6379
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    depends_on:
      - redis

  shogi-engine:
    build: ./shogi-engine
    ports:
      - '8002:8002'
    environment:
      - NODE_ENV=development

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
